# Generated by Django 5.2.13 on 2026-04-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='handover_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
